const shards = await runs.all([
  { key: 's01', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s01.json. Write /root/LearnDutch/dataset/shards/s01.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's02', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s02.json. Write /root/LearnDutch/dataset/shards/s02.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's03', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s03.json. Write /root/LearnDutch/dataset/shards/s03.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's04', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s04.json. Write /root/LearnDutch/dataset/shards/s04.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's05', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s05.json. Write /root/LearnDutch/dataset/shards/s05.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's06', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s06.json. Write /root/LearnDutch/dataset/shards/s06.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's07', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s07.json. Write /root/LearnDutch/dataset/shards/s07.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's08', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s08.json. Write /root/LearnDutch/dataset/shards/s08.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's09', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s09.json. Write /root/LearnDutch/dataset/shards/s09.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's10', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s10.json. Write /root/LearnDutch/dataset/shards/s10.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's11', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s11.json. Write /root/LearnDutch/dataset/shards/s11.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's12', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s12.json. Write /root/LearnDutch/dataset/shards/s12.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's13', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s13.json. Write /root/LearnDutch/dataset/shards/s13.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's14', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s14.json. Write /root/LearnDutch/dataset/shards/s14.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's15', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s15.json. Write /root/LearnDutch/dataset/shards/s15.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's16', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s16.json. Write /root/LearnDutch/dataset/shards/s16.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's17', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s17.json. Write /root/LearnDutch/dataset/shards/s17.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's18', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s18.json. Write /root/LearnDutch/dataset/shards/s18.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's19', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s19.json. Write /root/LearnDutch/dataset/shards/s19.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's20', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s20.json. Write /root/LearnDutch/dataset/shards/s20.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's21', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s21.json. Write /root/LearnDutch/dataset/shards/s21.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's22', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s22.json. Write /root/LearnDutch/dataset/shards/s22.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's23', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s23.json. Write /root/LearnDutch/dataset/shards/s23.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' },
  { key: 's24', agent: 'phraser', task: 'Read /root/LearnDutch/dataset/packs/s24.json. Write /root/LearnDutch/dataset/shards/s24.json with exactly pack.n sentences. Use only nouns/verbs/adjs in that pack plus function words from the phraser agent prompt. Theme and tags and level are in the pack. Honour de/het. Spoken Dutch. JSON array. audio null. Do not touch other shards.' }
]);
const merge = await runs.run("merge", {
  agent: 'worker',
  task: 'Run: python3 /root/LearnDutch/pipeline/merge.py && python3 /root/LearnDutch/pipeline/validate.py in /root/LearnDutch. If validate fails, fix sentences.json or the bad shard, rerun. Do not write 1000 sentences yourself. Report counts.'
});
return { ok: merge.ok, n: shards.length, output: merge.output };
